@startuml inventory
scale 1
title  "UML Class Diagram"
class Inventory {
	.. Instance Variables ..
	+ equip: int
	+ equipName: str
    + rockTotal: int
    + elaberrySeeds: int
    + honeyshroomSeeds: int
    + elaberryGrown: int
    + honeyshroomGrown: int
    .. Instance Methods ..
    + update(): None
}
@enduml