@startuml plant
scale 1
title  "UML Class Diagram"
class Plant {
	.. Instance Variables ..
	+ x: int
	+ y: int
    + plant_bounds: Rect
    + name: str
    + file_name: str
    + stage: int
    + max_stage: int
    - _harvested: bool 
    + plant_point: int
    .. Instance Methods ..
    + harvested(): None
}
@enduml