class RenderedText:
    tutorial1 = 'Use WASD keys to move.'
    tutorial2 = 'Press T to talk to the alien.'
    tutorial3 = 'Press I to open your inventory.'
    tutorial4 = 'Press T to talk to the shopkeeper.'
    tutorial5 = 'Press B to purchase seeds.'
    npc1 = 'I gift you 50 rocks.'
    npc2 = 'Hello there, strange one.'
    shop = '   SHOP:   '
    shop1 = '   B) Buy seeds   '
    shop2 = '   N) Sell plants   '
    purchase = '   O) Elaberry Seed: 10 rocks   '
    purchase1 = '   P) Honeyshroom Seed: 5 rocks   '